### ISSUE TITLE
[feature-request] Provide ARM binaries

### ISSUE THREAD

**Issue by TechHummel** [TLINDEN/kleingebaeck#81]
**Description**

Kleingebaeck is currently only available for amd64 architecture. I would like to run kleingebaeck on an ARM based server (Debian) without compiling the code myself 😀 
If you could add binaries for ARM (64bit) architecture, this would be very helpful.

Thanks for kleingebaeck 🥳

**Comment by TLINDEN** [comment]
Hi,

starting with release v0.3.5 there will be arm64 binaries available as well.

**Comment by TechHummel** [comment]
Just tested the ARM64 release of v0.3.5 - works like a charm! 👍
